app = "ghazi-rihal-codestacker"

[build]
  context = "./packages/backend" 

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

[[services]]
  internal_port = 5432
  protocol = "tcp"
  processes = ["postgres"]

  [[services.ports]]
    port = 5432
    handlers = ["tcp"]

[[volumes]]
  name = "pgdata"
  size = "1GB"
