version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: rds
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dccms
      POSTGRES_DB: dccms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c log_statement=all

volumes:
  pgdata:
