services:
  db:
    image: postgres:latest
    container_name: rds
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dccms
      POSTGRES_DB: dccms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c log_statement=all


volumes:
  pgdata:
